apiVersion: "kubeflow.org/v1alpha1"
kind: StudyJob
metadata:
  namespace: default
  labels:
    controller-tools.k8s.io: "1.0"
  name: random1-example-v2222
spec:
  studyName: random1-example-v2222
  owner: crd
  optimizationtype: maximize
  objectivevaluename: Validation-accuracy
  optimizationgoal: 0.99
  requestcount: 4
  metricsnames:
    - accuracy
  parameterconfigs:
    - name: --lr
      parametertype: double
      feasible:
        min: "0.01"
        max: "0.03"
    - name: --num-layers
      parametertype: int
      feasible:
        min: "2"
        max: "5"
    - name: --optimizer
      parametertype: categorical
      feasible:
        list:
        - sgd
        - adam
        - ftrl
  workerSpec:
    goTemplate:
      templatePath: "cpuWorkerTemplate.yaml"
  suggestionSpec:
    suggestionAlgorithm: "random"
    requestNumber: 3
